version = 0.1
[dev.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["ExpressFunction=637423407629.dkr.ecr.us-east-1.amazonaws.com/samapp7427b055/expressfunction9fcbc1barepo"]

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ExpressFunction=637423407629.dkr.ecr.us-east-1.amazonaws.com/samapp7427b055/expressfunction9fcbc1barepo"]
